server:
  port: 8203
  
spring:
  profiles: prod
  application:
    name: microservicecloud-config-client-prod
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-prod.com:7001/eureka/
---
server:
  port: 8204
  
spring:
  profiles: maintenance
  application:
    name: microservicecloud-config-client-maintenance
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
