server:
  port: 8202
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-TEST.com:7001/eureka/
